//
//  LLMChoice.swift
//  TextToSpeech
//
//  Created by Victor Brittes on 13/12/25.

/// A single choice returned by an LLM completion/response.
///
/// Wraps the assistant's generated `LLMMMessage` and conforms to `Codable`
/// for easy encoding/decoding when interacting with network responses.
struct LLMChoice: nonisolated Codable {
    
    /// The message content generated by the model for this choice.
    var message: LLMMMessage
    
}
